CREATE TABLE IF NOT EXISTS admins (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 username VARCHAR(80) NOT NULL UNIQUE,
 password_hash VARCHAR(255) NOT NULL,
 created_at DATETIME NOT NULL,
 last_login_at DATETIME NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS settings (
 `key` VARCHAR(120) PRIMARY KEY,
 value TEXT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS subscriptions (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 name VARCHAR(120) NOT NULL,
 url TEXT NOT NULL,
 active TINYINT(1) NOT NULL DEFAULT 1,
 priority INT NOT NULL DEFAULT 0,
 cached_nodes LONGTEXT NULL,
 node_count INT NOT NULL DEFAULT 0,
 last_error TEXT NULL,
 last_checked_at DATETIME NULL,
 cache_updated_at DATETIME NULL,
 created_at DATETIME NOT NULL,
 updated_at DATETIME NOT NULL,
 INDEX(active), INDEX(priority)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS ads (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 title VARCHAR(180) NOT NULL,
 image_path VARCHAR(255) NOT NULL,
 target_url TEXT NULL,
 placement VARCHAR(40) NOT NULL DEFAULT 'pre_connect',
 plan VARCHAR(30) NOT NULL DEFAULT 'free',
 display_seconds INT NOT NULL DEFAULT 4,
 priority INT NOT NULL DEFAULT 0,
 active TINYINT(1) NOT NULL DEFAULT 1,
 starts_at DATETIME NULL,
 ends_at DATETIME NULL,
 created_at DATETIME NOT NULL,
 updated_at DATETIME NOT NULL,
 INDEX(active), INDEX(priority)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS login_attempts (
 ip_hash CHAR(64) PRIMARY KEY,
 attempts INT NOT NULL DEFAULT 0,
 last_attempt DATETIME NOT NULL,
 lock_until DATETIME NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS schema_migrations (
 id VARCHAR(100) PRIMARY KEY,
 applied_at DATETIME NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
